spring.application.name=maintenance

spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:maintenance}
spring.datasource.username=${DB_USERNAME:maintenance}
spring.datasource.password=${DB_PASSWORD:maintenance}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
